[package]
name = "camera-server"
version.workspace = true
edition = "2024"

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
eframe = { workspace = true }
egui = { workspace = true }
camera-core = { workspace = true }
camera-ui = { workspace = true }
channel-masque = { workspace = true }
h3-util = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true, features = ["channel"] }
msquic-async = { workspace = true }
opencv = { workspace = true }
qrcode = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tower = { workspace = true, features = ["util"] }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
[target.'cfg(windows)'.dependencies]
schannel = { workspace = true }
